### ISSUE TITLE
Moltres init: cross-code or experimental comparison

### ISSUE THREAD

**Issue by gridley** [arfc/publications#40]
Address:

> It's somehow interesting that "For some three-dimensional simulations, the number of elements in the mesh and total number of degrees of freedom exceed one million and ten million respectively. To handle problems of this size, we ran Moltres on up to 608 cores." Normally problems of few million degrees of freedom can be handled with few tens of cores. The authors should discuss more extensively the performances of their code in order to give the reader the possibility to compare them with those of other tools. In particular, it is possible that slow performances may derive from trying to achieve a fully coupled solution (i.e., all the equations in the same matrix), which seems to be the case in this work. In this sense and to better support the claims of the paper, it would be important to compare the performances of a segregated and a fully coupled  solver, both in terms of accuracy and computational time. In addition to helping supporting the claims of the paper, this
would represent a significant contribution to the scientific community, since many of the currently available tools employ segregated solvers, and since the advantages and disadvantages of a fully coupled solver are often a subject of discussion.

Maybe we could get in contact with Ben Collins at ORNL who presented on CASL's MSR efforts. They implemented MOC neutronics on a fluid-fueled system described [here](http://ansannual.org/wp-content/data/polopoly_fs/1.3583831.1494346729!/fileserver/file/768091/filename/365.pdf). Since Dr. Collins's group used some fancy transport approximations, their code likely has far-superior fidelity per unit computation. We could argue that Moltres should serve as a testbed for various computational approaches to MSRs before developing high performance, lower level codes that don't rely on explicitly forming a problem matrix.

Also, a note on comparing fully coupled and decoupled calculation: IIRC, CASL-VERA running LWR full-core depletion simulation takes a week on 1000 cores for decoupled calculations, and three weeks on the same number of cores for fully coupled mode. We may be able to get some data from our ORNL friends for comparison.

**Comment by katyhuff** [comment]
MPACT - MSR features?

**Comment by gridley** [comment]
OK, here's how I'd like to address this. I'd run a 2D axisymmetric case in both coupled and decoupled mode, both steady state and transient, and a coarse and fine mesh, for 8 cases total. This would give info about the effects of coupling. In particular, the transient cases should illustrate the importance of fully coupling, especially with higher reactivity insertions. I'm just not sure what transient case would be best... probably the control rod movement.

**Comment by gridley** [comment]
@lindsayad it seems like this issue sort of coincides with issue #43. Maybe I could set up the transient cases, and then you modify them for both a decoupled and a fully coupled solution? If that's not too much burden for you, that is.

**Comment by lindsayad** [comment]
I would contend that the title of this issue doesn't really match the associated reviewer quote. Instead as you say I think this quote belongs with issue #43. More closely associated with the title of this issue is in the reviewer's summary:
> The paper would represent an interesting contribution to the scientific community but it requires revision. In  particular the authors should deepen their bibliographical research, and include a comparison either with experimental results or with other state-of-the-art tools.

There is certainly overlap. I guess in a perfect world with unlimited time we would try to produce the "best" results with Moltres any way we can. When there are trustworthy experimental results, there is no ambiguity about what "best" means; the calculations should reproduce the experimental results. However, if there aren't trustworthy experimental results then who is to say what is best? How can we really say what model is high fidelity and what isn't? We use a more _a priori_ model, a finer mesh, higher degree polynomials, full physics coupling? Yes things like that are more _probably_ more likely to produce a more physical result but we just don't know without real results. 

I also don't really know how the reviewer got "slow performance" in his/her head. Is he assuming that because we use a lot of cores? 

> Normally problems of few million degrees of freedom can be handled with few tens of cores.

My response to that would be: if you have the resources, why not use them? Why solve something in an hour if you have the parallelizability to solve it in minutes?!

So returning to practical matters @gridley, I think it would be great if you (or anybody) could try and do some comparison to experimental or other codes' results using our default fully coupled treatment. That addresses the title of this issue in my mind. In terms of "high fidelity", there is no reason that full coupling shouldn't be just as or more accurate than a segregated approach. **Then** to address issue #43 we can compare segregated to monolithic calculations (which we can then also of course use in comparison to the experimental/cross-code results). So yes definitely some overlap, but I think we can keep both open. Waddya think? (after my  long diatribe)

**Comment by lindsayad** [comment]
I should say that if you iterate between physics and use the same tolerances in a segregated as in a monolithic solve, then the accuracy of the two solution methods should be the same. It's just that in very tight physics couplings, the iterative segregated approach may not converge. Also the resources used will probably be different. Fully coupled may use a lot more memory for example, but may also be faster. We won't know that until we try. I think resource comparison falls under the umbrella of #43

**Comment by andrewryh** [comment]
So far only found measurements for  control rod worth in zero power state: http://moltensalt.org/references/static/downloads/pdf/ORNL-TM-1626.pdf
Keep digging

@lindsayad @gridley Why you don't want to cross-verify moltres with Cammi's Comsol model?

**Comment by andrewryh** [comment]
I found some neutron flux profile, which slightly lower than reference used in moltres paper _**(fast flux ~11 instead of 14)**_. Looks like it some simulation (not an experiment) but, probably, useful: 
![temp_and_neutron_fluxes_ornl-3872](https://user-images.githubusercontent.com/20629016/31344271-d4d5397c-acd7-11e7-86c6-fb8e2a21b1cc.png)

Source: http://www.thmfgrcs.com/ORNL-3872.pdf

**Comment by lindsayad** [comment]
Hmm, would still like to find some experimental results if possible! But
yea this is good. Thanks for doing this digging Andrei

On Mon, Oct 9, 2017 at 8:55 AM, Andrei Rykhlevskii <notifications@github.com

**Comment by andrewryh** [comment]
Yea, I still try to find experimental data, 22 semiannual reports, 300-40 page each, take time :)
Don't believe in conspiracy theory but looks like someone intentionally didn't include interesting flux and temperature measurements in those reports...

**Comment by lindsayad** [comment]
I know it was incredibly frustrating for me when I was perusing the reports
the first time!!!

On Mon, Oct 9, 2017 at 9:10 AM, Andrei Rykhlevskii <notifications@github.com

**Comment by gridley** [comment]
So, @lindsayad @andrewryh, what do you al lsay that we reproduce Cammi results for the single channel? The mesh would be simple, and IIRC we already have all of the physics coded in that they use. I think the biggest difference would be computing cross sections from parsed functions rather than interpolation tables. Also, they used a k-\epsilon turbulence model, which @lindsayad got working, right?

There are a few things we could reproduce, and not all would be necessarily needed. It seems that they calculate feedback coefficients in an infinite reflecting channel in eigenvalue calculation mode, which would be relatively easy after getting the mesh made since we could use Cammi's group constants.

In terms of the fluids part, we could use Alex's Petrov-Galerkin scheme that allows P1 lagrange velocity variables (which I have no clue how to use, is this online?).

Well, this seems like a lot, but we have a lot of time and could set up a small timeline if needed. :smile:

**Comment by katyhuff** [comment]
@gridley (you didn't ask me, but ... ) This is a good idea and worthwile endeavor, but I have 2 concerns.

1) I don't think reproducing the Cammi single channel result completely satisfies the desire expressed by the reviewer (who desired comparison to high fidelity simulations or experiment). It would be a helpful example, certainly, but experimental validation or high-fidelity-code-to-code verification. While the single channel model represents a modern simulation with coupled physics, our feature claims in this paper are related to more complex geometries (2-D axisymmetric many channel and 3-D many channel), so they should be verified against complex geometries, IMO.

2) Alex tried to replicate Cammi and failed to get agreement early on in Fall 2016, likely based on miscommunication in their paper which was never clarified despite many attempts to clarify it with the authors (is that this same single channel example, @lindsayad ? I forgot.)

**Comment by lindsayad** [comment]
This doesn't affect the worthwhileness of the endeavor, but isn't that
single channel for MSBR? Anyways, yea I tried reproducing and failed. We
would need their cross sections in order to reproduce. What I found was
with the cross sections I generated in scale and the geometry definition
given by the Cammi paper, the reactor was majorly super-critical, like k =
1.2 or something like that. And as @kdhuff said, I tried contacting Luzzi
and Cammi multiple times and got no response. Maybe Manuele could help; I
don't know.

**Comment by lindsayad** [comment]
Regarding the turbulence model, that was never finished as it really
required SUPG stabilization to be relevant. At the time I hadn't yet
implemented SUPG and PSPG in the navier-stokes module but now both are
there. So the k-epsilon model could be finished if someone wanted to work
on it; however, that won't be me. It's very close to completion; the major
piece remaining are the wall functions.

**Comment by gridley** [comment]
Well, I have contact both Manuele and Dr. Collins over the past two weeks, and they seem hesitant to let go of any data at the moment. So, on this front, we may be stuck unless some experimental results are found. We could possibly use these cross sections I found from Cammi in a[ presentation here](https://www.comsol.com/paper/download/45630/Di_Marcello_pres.pdf) and see if our cross sections look anything like that. @lindsayad, where are the group constants you generated, out of curiosity?

![cammigc](https://user-images.githubusercontent.com/18088906/31399191-700e6292-adb9-11e7-860b-cf7f313ecad5.png)

**Comment by lindsayad** [comment]
Honestly not entirely sure if these are them but they may be in the
`property_file_dir`, newt_fuel_(XS).txt and newt_mod_(XS).txt

**Comment by gridley** [comment]
Hm, right, I see how your results would be supercritical because, judging from property_file_dir/newt_fuel_NSF.txt, your NSF cross sections for fast and thermal groups are respectively 22% and 30% higher than Cammi's presentation. I'm going to plug this single channel into Serpent and see what happens. I'd imagine some discrepancy could arise due to collapsing XSs in the supercritical spectrum rather than critical, and Serpent definitely does leakage corrections before averaging over the spectrum. As for NEWT, no clue.

**Comment by gridley** [comment]
Well, OK, even if your case was quite supercritical @lindsayad, Cammi et. al. did add artrificial neutron poison, and from what I've found they don't provide how much Sigma_a was perturbed by. It may have been large.

**Comment by lindsayad** [comment]
The wonders of trying to reproduce science :-(

**Comment by lindsayad** [comment]
Not finished for this paper per se, but we left comments on this point.

Closed by #66
