### ISSUE TITLE
Fissile inventory

### ISSUE THREAD

**Issue by lindsayad** [arfc/publications#64]
Reviewer question:

> In the introduction, the authors mention that: ``Two key advantages
> offered by the fluid-fuelled MSR are improved fuel utilization and no radiation
> damage constraint on attainable fuel burn-up. Together, these attributes result
> in significantly reduced core fissile inventories and spent nuclear fuel mass''
> However, the fissile inventory is not necessarily related to fuel burnup and
> fuel utilization. It can actually be very high in chloride-based fast-spectrum
> MSRs.

Anyone got a shot at this one?

**Comment by katyhuff** [comment]
I have to go teach class -- will be occupied for the next couple of hours. I'd say, clarify the sentence to refer to fluoride salts. e.g. Together, these attributes can result in significantly reduced spent fuel mass and, in the case of fluoride salt reactors in particular, reduced core fissile inventories."

**Comment by gridley** [comment]
on it!

**Comment by gridley** [comment]
To be honest with you guys, I think the "lower core fissile inventory" claim isn't a good one unless a reactor designer comes up with a good way to limit graphite fast neutron fluence without bringing leakage way up. If you look at some of the last work from ORNL's molten salt glory days ([7207](http://www.energyfromthorium.com/pdf/ORNL-TM-7207.pdf)) you'll see that they generally considered large, low power density cores the key to building a cheap thermal MSR. Higher power densities imply changing out core graphite quite frequently, since the irradiation limit before losing structural integrity is lower than you'd think.

And sure, there's zirc hydride, but for one little paragraph, that would be getting out of scope.

**Comment by lindsayad** [comment]
Closed by #65
